[metadata]
name = ipc-cfx
version = 0.1.0
author = Rosen Vladimirov
author_email = your.email@example.com
description = IPC Connected Factory Exchange Open Source Software Development Kit.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/rosenvladimirov/ipc_cfx
license = MIT
keywords = ipc, cfx, factory, automation, manufacturing, connected factory exchange
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Manufacturing
    Intended Audience :: Information Technology
    License :: OSI Approved :: AGPL
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Topic :: Manufacturing
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Industrial Automation

[options]
packages = find:
package_dir =
    =src
python_requires = >=3.9
install_requires =
    requests>=2.25.0
    websockets>=10.0

[options.packages.find]
where = src
include =
    lib*
exclude =
    tests*
    docs*

[options.package_data]
* = *.xml, *.json
