[metadata]
name = ipc-cfx
version = 0.1.0
author = Rosen Vladimirov
author_email = your.email@example.com
description = IPC Connected Factory Exchange Open Source Software Development Kit.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/rosenvladimirov/ipc_cfx
license = LGPL-3.0-or-later
keywords = ipc, cfx, factory, automation, manufacturing, connected factory exchange
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Manufacturing
    Intended Audience :: Information Technology
    License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Topic :: Manufacturing
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Industrial Automation

[options]
packages = find:
package_dir =
    =src
python_requires = >=3.10
install_requires =
    rabbitmq-amqp-python-client>=0.8.0
    requests>=2.25.0
    inflection>=0.5.1
    xmltodict>=0.13.0
    dicttoxml2>=2.1.0

[options.packages.find]
where = src
include =
    lib*
    server*
exclude =
    tests*
    docs*

[options.entry_points]
console_scripts =
    ipc-cfx = server.main:main

[options.package_data]
* = *.xml, *.json
